export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const DROP_EXERCISE_SUCCESS = 'DROP_EXERCISE_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
